[package]
name = "dozer"
version = "0.1.0"
edition = "2021"
authors = ["Jeff Schwab <jeff@unbuggy.com>"]

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.5.2", features = ["csr", "nightly"] }
